# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
 use_frameworks!

target 'iOSV1' do
 pod 'SwiftyJSON', '~> 2.3'
 pod 'Charts', '2.2.3'
 pod 'Firebase'
 pod 'Firebase/Core'
 pod 'Firebase/Database'
 pod 'Firebase/Auth'
end

target 'iOSV1Tests' do

end

